{% set version = "3.7.3" %}

package:
  name: configparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/configparser/configparser-{{ version }}.tar.gz
  sha256: 27594cf4fc279f321974061ac69164aaebd2749af962ac8686b20503ac0bcf2d

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - backports
    - pip
    - python
  run:
    - backports
    - python

test:
  imports:
    - backports
    - backports.configparser
    - configparser

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  license_file: LICENSE
  summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
