{% set version = "3.5.0" %}

package:
    name: configparser
    version: {{ version }}

source:
    fn: configparser-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/c/configparser/configparser-{{ version }}.tar.gz
    md5: cfdd915a5b7a6c09917a64a573140538

build:
    number: 0
    skip: True  # [py>34]
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    host:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - backports
        - backports.configparser
        - configparser

about:
    home: http://docs.python.org/3/library/configparser.html
    license: MIT
    summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5
    description: |
      This module provides the ConfigParser class which implements a basic
      configuration language which provides a structure similar to what's
      found in Microsoft Windows INI files.
    doc_url: https://docs.python.org/3/library/configparser.html
    dev_url: https://github.com/python/cpython/tree/3.6
    doc_source_url: https://github.com/python/cpython/blob/3.6/Doc/library/configparser.rst

extra:
    recipe-maintainers:
        - jakirkham
        - ocefpaf
