{% set name = "configparser" %}
{% set version = "7.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b629cc8ae916e3afbd36d1b3d093f34193d851e11998920fdcfc4552218b7b70

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python

test:
  requires:
    - pip
  imports:
    - backports
    - backports.configparser
    - configparser
  commands:
    - pip check

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  license_file: LICENSE
  summary: Updated configparser from Python 3.8 for Python 2.6+.
  description: |
      This module provides the ConfigParser class which implements a basic
      configuration language which provides a structure similar to what's
      found in Microsoft Windows INI files.
  doc_url: https://docs.python.org/3/library/configparser.html
  doc_source_url: https://github.com/python/cpython/blob/3.6/Doc/library/configparser.rst

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
