{% set version = "3.7.4" %}

package:
  name: configparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/configparser/configparser-{{ version }}.tar.gz
  sha256: da60d0014fd8c55eb48c1c5354352e363e2d30bbf7057e5e171a468390184c75
  patches:
    # only needed on Windows + 3.x. Pip uses distutils to load the
    # configuration and defaults to cp1252 encoding
    - 0001-use-ascii-in-setup.cfg.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - backports
    - pip
    - python
  run:
    - backports
    - python

test:
  imports:
    - backports
    - backports.configparser
    - configparser

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  license_file: LICENSE
  summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5
  description: |
      This module provides the ConfigParser class which implements a basic
      configuration language which provides a structure similar to what's
      found in Microsoft Windows INI files.
  doc_url: https://docs.python.org/3/library/configparser.html
  doc_source_url: https://github.com/python/cpython/blob/3.6/Doc/library/configparser.rst

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
