{% set version = "3.7.3" %}

package:
  name: configparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/configparser/configparser-{{ version }}.tar.gz
  sha256: 27594cf4fc279f321974061ac69164aaebd2749af962ac8686b20503ac0bcf2d

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - backports
    - pip
    - python
  run:
    - backports
    - python

test:
  imports:
    - backports
    - backports.configparser
    - configparser

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  license_file: LICENSE
  summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5
  description: |
      This module provides the ConfigParser class which implements a basic
      configuration language which provides a structure similar to what's
      found in Microsoft Windows INI files.
  doc_url: https://docs.python.org/3/library/configparser.html
  doc_source_url: https://github.com/python/cpython/blob/3.6/Doc/library/configparser.rst

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
