travis:
  secure:
    BINSTAR_TOKEN: WSGtKdhBi0Ae5ENgzGBsMpxLGHNByKSiJqJp1+fpTujA4uJKImFtDSkhKukrZHqIXVarJuaAunvSgZD4IsZ0RnUi5sqsPAdxprzd9GpjHZcpR8awY0Rkny2D6BpKQ7jU+GSIQ6A40EbUnP3Mhkd+yJt/1QZXSEOWfgSfjPfK1dVw1z3Kvy6ULuRi3dBDpqSK6ITZlbmC81v4vsur6k5qHYJt7JC7AWZsesNJyEIPGqqSamjKoeTVaebla/8MRWQUbcvuZdhCKj94rKdMbfx9VQfRmR4HebEKshWK1DY3x4++ROLxyd8U2SiYy+MLREzws2TiRIdURY2o85xu6BDoduu66GVeBSY69Jcg03rEelqYB1/FkxJwkp7NFyj0sQ90D+gp9ZrLfSbCBNBpOKPLd+0v85XBmefgzm6bPw451AzOYqV5x0HRG/mYo6GJZXHMmFQswbmeVC4rb0ChQ/cfU+n3iDb1dpOjiRFIzXJ5KdMHoz3WcckrdUE+JUfmwkd+4EddIdzXQLRmQmrwzbC609W17nQWIYBX6BhIZDYUE/ocONfVpHvjQDz6YcG5PTrPZ/y+eVCFjrBOGHkW+vkee60jcPjf8QKCV5dQ156ZIkg/yvhS5MENp19jWqh9Xcuf64UqWnmFQCCKPmjF4joyt7YjdkkIImMcQRekzbEinac=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
